/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nibble.supermarket.vista;

import com.nibble.supermarket.logicaVista.CtrlMantenimientoClientes;
import com.nibble.supermarket.logicaVista.CtrlMantenimientoEmpleados;
import com.nibble.supermarket.logicaVista.CtrlMantenimientoProductos;
import javax.swing.JFrame;
import javax.xml.crypto.dsig.spec.C14NMethodParameterSpec;

/**
 *
 * @author USUARIO
 */
public class MainAdministrador extends javax.swing.JFrame {

    MantenimientoClientes v1;
    MatenimientoEmpleados v2;
    MantenimientoProductos v3;
    
    public MainAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMainAdministrador = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subMantClientes = new javax.swing.JMenuItem();
        subAdmEmpleados = new javax.swing.JMenuItem();
        subMantProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpMainAdministrador.setBackground(new java.awt.Color(230, 244, 245));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image-admin.png"))); // NOI18N

        jdpMainAdministrador.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpMainAdministradorLayout = new javax.swing.GroupLayout(jdpMainAdministrador);
        jdpMainAdministrador.setLayout(jdpMainAdministradorLayout);
        jdpMainAdministradorLayout.setHorizontalGroup(
            jdpMainAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpMainAdministradorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdpMainAdministradorLayout.setVerticalGroup(
            jdpMainAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpMainAdministradorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        subMantClientes.setText("Mantenimiento de clientes");
        subMantClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMantClientesActionPerformed(evt);
            }
        });
        jMenu1.add(subMantClientes);

        subAdmEmpleados.setText("Mantenimineto de empleados");
        subAdmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAdmEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(subAdmEmpleados);

        subMantProductos.setText("Mantenimiento de productos");
        subMantProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMantProductosActionPerformed(evt);
            }
        });
        jMenu1.add(subMantProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpMainAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpMainAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMantClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMantClientesActionPerformed
        if (v1 == null || v1.isClosed()) {
            v1 = new MantenimientoClientes();
            CtrlMantenimientoClientes c1 = new CtrlMantenimientoClientes(v1);
            
            jdpMainAdministrador.add(v1); //Agregamos al JDesktopPane

            //Para que aparezca en el centro
            int x = (jdpMainAdministrador.getWidth() - v1.getWidth()) / 2;
            int y = (jdpMainAdministrador.getHeight() - v1.getHeight()) / 2;
            v1.setLocation(x, y);
            
            c1.iniciar();
        } 
    }//GEN-LAST:event_subMantClientesActionPerformed

    private void subAdmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAdmEmpleadosActionPerformed
        if (v2 == null || v2.isClosed()) {
            v2 = new MatenimientoEmpleados();
            CtrlMantenimientoEmpleados c2 = new CtrlMantenimientoEmpleados(v2);
            
            jdpMainAdministrador.add(v2); //Agregamos al JDesktopPane

            //Para que aparezca en el centro
            int x = (jdpMainAdministrador.getWidth() - v2.getWidth()) / 2;
            int y = (jdpMainAdministrador.getHeight() - v2.getHeight()) / 2;
            v2.setLocation(x, y);
            
            c2.iniciar();
        } 
    }//GEN-LAST:event_subAdmEmpleadosActionPerformed

    private void subMantProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMantProductosActionPerformed
        if (v3 == null || v3.isClosed()) {
            v3 = new MantenimientoProductos();
            CtrlMantenimientoProductos c3 = new CtrlMantenimientoProductos(v3);
            
            jdpMainAdministrador.add(v3); //Agregamos al JDesktopPane

            //Para que aparezca en el centro
            int x = (jdpMainAdministrador.getWidth() - v3.getWidth()) / 2;
            int y = (jdpMainAdministrador.getHeight() - v3.getHeight()) / 2;
            v3.setLocation(x, y);
            
            c3.iniciar();
        }
    }//GEN-LAST:event_subMantProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JDesktopPane jdpMainAdministrador;
    private javax.swing.JMenuItem subAdmEmpleados;
    public javax.swing.JMenuItem subMantClientes;
    private javax.swing.JMenuItem subMantProductos;
    // End of variables declaration//GEN-END:variables
}
