/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nibble.supermarket.vista;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.*;

 
public class Main extends javax.swing.JFrame  {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Repetición p1 = new Repetición();
        InitContent(p1);
        
        
    }
    
    private void InitContent(JPanel p){
        p.setSize(860, 480);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnVentas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnRepeticion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        BtnAnulacion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 211, 176));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("NombreUsuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Conectado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/llogin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-linea.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 195, -1, -1));

        jLabel2.setBackground(new java.awt.Color(250, 172, 119));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 230));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-cerrar.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-registrar.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        BtnVentas.setBackground(new java.awt.Color(240, 240, 240));
        BtnVentas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnVentas.setText("Ventas");
        BtnVentas.setToolTipText("");
        BtnVentas.setBorder(null);
        BtnVentas.setBorderPainted(false);
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-repetir.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        BtnRepeticion.setBackground(new java.awt.Color(240, 240, 240));
        BtnRepeticion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnRepeticion.setText("Repetición");
        BtnRepeticion.setBorderPainted(false);
        BtnRepeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepeticionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRepeticion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon-borrar.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(252, 203, 166));
        btnCerrarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 350, 70));

        BtnAnulacion.setBackground(new java.awt.Color(240, 240, 240));
        BtnAnulacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnAnulacion.setText("Anulación");
        BtnAnulacion.setBorderPainted(false);
        BtnAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnulacionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAnulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 350, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 780));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel13.setText("SUPERMARKET NIBBLE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(250, 172, 119));
        jLabel1.setOpaque(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1080, 120));

        content.setBackground(new java.awt.Color(204, 204, 204));
        content.setAlignmentX(0.0F);
        content.setAlignmentY(0.0F);
        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        scaner s = new scaner();
        s.setLocationRelativeTo(this);
        s.setVisible(true);
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void BtnRepeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepeticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRepeticionActionPerformed

    private void BtnAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnulacionActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnulacion;
    private javax.swing.JButton BtnRepeticion;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
